server:
  port: 8054
spring:
  application:
    name: oderservice
  datasource:
    url: jdbc:mysql://localhost:3306/products?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

