server:
  port: 8054
spring:
  application:
    name: Order_Service
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    client:
      serverUrl:
        defautlZone: http://localhost:8761/eureka/

rest-template:
  user:
    url: http://localhost:8081/user/

